name: Deploy Python App to EC2

on:
  push:
    branches:
      - main  # Deploy when pushing to 'main' branch

jobs:
  deploy:
    runs-on: Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/your-repo
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
